baseURL = "https://ceresia.vision"
languageCode = "es"
title = "Ceresia Vision"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.jpg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"

  [params.homepage_meta_tags]
    meta_description = "Ceresia es una compañia dedicada a la inteligencia artificial para el analisis de la uva"
    meta_og_title = "Ceresia"
    meta_og_type = "website"
    meta_og_url = "https://ceresia.vision"
    meta_og_image = "https://ceresia.vision/images/segmentada.jpeg"
    meta_og_description = "Ceresia es una compañia dedicada a la inteligencia artificial para el analisis de la uva"
    meta_twitter_card = "summary"
    meta_twitter_site = "@ceresia"
    meta_twitter_creator = "@ceresia"


[[menu.main]]
    name = "Ceres Uva"
    url = "/ceresuva/"
    weight = 1

[[menu.main]]
    name = "Contacto"
    url = "/contact/"
    weight = 4

[[menu.main]]
    name = "Demo"
    url = "https://demo.ceresia.vision"
    weight = 3


[[menu.main_mobile]]
    name = "Ceres Uva"
    url = "/ceresuva/"
    weight = 1

[[menu.main_mobile]]
    name = "Contacto"
    url = "/contact/"
    weight = 4



[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
